### PR TITLE
Rails 7.1 upgrade

### PR DESCRIPTION
**Pull request by ryanb-gds**
Trello: https://trello.com/c/UPcdP6Xc/1812-upgrade-manuals-publisher-to-rails-71

Would appreciate a particularly close look from reviewers at the config changes in `config/environments`, as those needed to be merged manually. I based my merge off of the changes in [the upgrade to Maslow](https://github.com/alphagov/maslow/pull/1057), but that may not include everything needed by Manuals Publisher.

There was also something a bit odd where the assets seem to be compiled to a slightly different location inside the public directory, meaning I had to update the jasmine config. Everything else seems to be ok though.

### CODE REVIEW

**Comment by ryanb-gds** [comment]
Tested this in integration, seems to be working well.

**Comment by ryanb-gds** [comment]
Ok, pretty sure I've genuinely succeeded in testing this in integration this time. Looks like it should be good to go

**Review by sengi — APPROVED** [review]
Thanks!

**Review by davidgisbey — COMMENTED** [review]
sorry i forgot to say i looked at this. All looked good to me too

**Pull request merged**
