### PR TITLE
Inline SectionPublishingAPIExporter into PublishingAdapter

### PR DESCRIPTION
**Pull request by floehopper**
This continues the work to [extract API adapters from exporters][1].

Note that this results in `PublishingAdapter#save_section_content` becoming a very big method. However, I think it's a lot clearer what's going on and I'm hopeful that once I've also inlined `ManualPublishingAPIExporter`, I'll be able to extract some useful abstractions which will make the code terser.

[1]: https://github.com/alphagov/manuals-publisher/issues/996

### CODE REVIEW

**Comment by floehopper** [comment]
Rebasing against master and force-pushing.

**Comment by floehopper** [comment]
Splitting a commit into two, rebasing against master and force-pushing.

**Comment by chrisroos** [comment]
This looks good to me, @floehopper.

The only very, very minor thing I spotted was in a commit message. The commit with subject, "Use attribute reader methods vs fetching from attributes Hash" contains "and a `Section` never has a `content_id`" where I think it should be "and an `Attachment` never has a `content_id`".

**Comment by floehopper** [comment]
@chrisroos: Thanks.

Rebased against master, fixed commit message, and force-pushed in preparation for merging.

**Pull request merged**
